spring:
  # H2 Setting
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver  # dev only, prod db : mysql
#    url: jdbc:h2:~/test
#    username: sa
#    password: test123

  # MySQL Setting
  datasource:
    url: jdbc:mysql://222.109.210.214:3306/mosinsa
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  # Security Setting
  security:
    user:
      name: test
      password: test


# log level Setting
logging:
  level:
    org.hibernate.type: trace

# Embedded Tomcat Setting
server:
  port: 9090
